// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNMMR6yH3hAgM_nx9MgnC0MTTzSreaY0',
    appId: '1:611973519183:web:44d3d06d8eb6eb7d04973a',
    messagingSenderId: '611973519183',
    projectId: 'spotify01-e0f2c',
    authDomain: 'spotify01-e0f2c.firebaseapp.com',
    storageBucket: 'spotify01-e0f2c.firebasestorage.app',
    measurementId: 'G-R108WMMKN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7BuCPvkVuftXsldZzErrkFoQcH15Ebg',
    appId: '1:611973519183:android:56f8c286dc75879604973a',
    messagingSenderId: '611973519183',
    projectId: 'spotify01-e0f2c',
    storageBucket: 'spotify01-e0f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtcetv_5p2WqGbCND4dB273WVhqwj2Ng',
    appId: '1:611973519183:ios:d89c0eac5ad9c83104973a',
    messagingSenderId: '611973519183',
    projectId: 'spotify01-e0f2c',
    storageBucket: 'spotify01-e0f2c.firebasestorage.app',
    iosBundleId: 'com.example.spotifyAppJavierMartinez4sa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWtcetv_5p2WqGbCND4dB273WVhqwj2Ng',
    appId: '1:611973519183:ios:d89c0eac5ad9c83104973a',
    messagingSenderId: '611973519183',
    projectId: 'spotify01-e0f2c',
    storageBucket: 'spotify01-e0f2c.firebasestorage.app',
    iosBundleId: 'com.example.spotifyAppJavierMartinez4sa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNMMR6yH3hAgM_nx9MgnC0MTTzSreaY0',
    appId: '1:611973519183:web:a6f04736a68da70604973a',
    messagingSenderId: '611973519183',
    projectId: 'spotify01-e0f2c',
    authDomain: 'spotify01-e0f2c.firebaseapp.com',
    storageBucket: 'spotify01-e0f2c.firebasestorage.app',
    measurementId: 'G-V2WLB0R4LT',
  );
}
